sudo: required
before_install:
- sudo apt-get update -qq
- sudo apt-get install texlive-latex-base
script:
- mkdir tmp
- mkdir output
- pdflatex -output-directory output source/document.tex
deploy:
  provider: releases
  file:
    - output/root.pdf
  skip_cleanup: true
  on:
    tags: true
